spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/app
    username: postgres
    password: 12345
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    enabled: true
